name: efficacy_user
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.2+11

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  font_awesome_flutter: ^10.6.0
  flutter_svg: ^2.0.8
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl_phone_number_input: ^0.7.3+1
  expandable: ^5.0.1
  intl_phone_field: ^3.2.0
  intl: ^0.18.1
  provider: ^6.0.5
  flutter_image_compress: ^2.1.0
  workmanager: ^0.5.2
  image_cropper: ^5.0.0
  easy_stepper: ^0.8.1
  flutter_local_notifications: ^16.1.0
  permission_handler: ^11.0.1
  google_sign_in: ^6.1.5
  native_flutter_proxy: ^0.1.15
  crypt: ^4.3.1
  flutter_dotenv: ^5.1.0
  mongo_dart: ^0.9.3
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  cloudinary: ^1.2.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  url_launcher: ^6.1.14
  photo_view: ^0.14.0
  path_provider: ^2.1.1
  focused_menu: ^1.0.2
  share_plus: ^7.2.2
  feedback: ^3.0.0
  tutorial_coach_mark: ^1.2.11
  pdf: ^3.10.7
  device_info_plus: ^9.1.2
  mailer: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/developers_data/
    - .env
    - assets/images/


  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/Sofia_Pro/SofiaProLight.ttf
          weight: 300
        - asset: assets/fonts/Sofia_Pro/SofiaProRegular.ttf
          weight: 400
        - asset: assets/fonts/Sofia_Pro/SofiaProMedium.ttf
          weight: 500
        - asset: assets/fonts/Sofia_Pro/SofiaProSemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sofia_Pro/SofiaProBold.ttf
          weight: 700
        - asset: assets/fonts/Sofia_Pro/SofiaProBlack.ttf
          weight: 900